apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: virt
spec:
  version: "{{ .TagName }}"
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/kubevirt/kubectl-virt-plugin/releases/download/{{ .TagName }}/virtctl-darwin-amd64.tar.gz" .TagName }}
    files:
    - from: "/virtctl/virtctl-darwin-amd64"
      to: "virtctl"
    - from: virtctl/LICENSE
      to: .
    bin: "virtctl"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/kubevirt/kubectl-virt-plugin/releases/download/{{ .TagName }}/virtctl-darwin-arm64.tar.gz" .TagName }}
    files:
    - from: "/virtctl/virtctl-darwin-arm64"
      to: "virtctl"
    - from: virtctl/LICENSE
      to: .
    bin: "virtctl"
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/kubevirt/kubectl-virt-plugin/releases/download/{{ .TagName }}/virtctl-linux-amd64.tar.gz" .TagName }}
    files:
    - from: "/virtctl/virtctl-linux-amd64"
      to: "virtctl"
    - from: virtctl/LICENSE
      to: .
    bin: "virtctl"
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/kubevirt/kubectl-virt-plugin/releases/download/{{ .TagName }}/virtctl-linux-arm64.tar.gz" .TagName }}
    files:
    - from: "/virtctl/virtctl-linux-arm64"
      to: "virtctl"
    - from: virtctl/LICENSE
      to: .
    bin: "virtctl"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/kubevirt/kubectl-virt-plugin/releases/download/{{ .TagName }}/virtctl-windows-amd64.exe.tar.gz" .TagName }}
    files:
    - from: "/virtctl/virtctl-windows-amd64.exe"
      to: "virtctl.exe"
    - from: virtctl/LICENSE
      to: .
    bin: "virtctl.exe"
  shortDescription: Control KubeVirt virtual machines using virtctl
  homepage: https://github.com/kubevirt/kubectl-virt-plugin
  caveats: |
    virt plugin is a wrapper for virtctl originating from the KubeVirt project. In order to use virtctl you will
    need to have KubeVirt installed on your Kubernetes cluster to use it. See https://kubevirt.io/ for details

    See

      https://kubevirt.io/user-guide/virtual_machines/accessing_virtual_machines/#graphical-and-serial-console-access

    for a usage example
  description: |
    virt plugin is a wrapper for virtctl originating from the KubeVirt project. KubeVirt is a virtualization add-on to
    Kubernetes, i.e. it enables to run existing virtual machines on Kubernetes clusters. virtctl controls virtual
    machine related operations on your Kubernetes cluster like connecting to the serial and VNC consoles.

    Kubevirt documentation:
      Installation:
        https://kubevirt.io/user-guide/operations/installation/
      User Guide:
        https://kubevirt.io/user-guide/
      Minikube Quickstart:
        https://kubevirt.io/quickstart_minikube/
      Virtctl usage examples:
        https://kubevirt.io/user-guide/virtual_machines/accessing_virtual_machines/#graphical-and-serial-console-access
        https://kubevirt.io/user-guide/virtual_machines/service_objects/#expose-virtualmachineinstance-as-a-loadbalancer-service
        https://kubevirt.io/user-guide/virtual_machines/replicaset/
